DEFAULT_RECIPES = [
    {'name': 'Poulet rôti aux herbes & légumes racines', 'category': 'Viande', 'art_key': 'chicken',
     'ingredients': ['Poulet', 'Pommes de terre', 'Carottes', 'Panais', 'Ail', "Huile d'olive", 'Romarin']},
    {'name': "Tajine d'agneau", 'category': 'Viande', 'art_key': 'lamb',
     'ingredients': ['Agneau', 'Oignon', 'Épices tajine', 'Amandes', 'Riz']},
    {'name': 'Sauté de bœuf aux poivrons et riz', 'category': 'Viande', 'art_key': 'beef',
     'ingredients': ['Bœuf', 'Poivrons', 'Oignon', 'Ail', 'Tamari (sauce soja sans gluten)', 'Riz']},
    {'name': 'Boulettes de bœuf, sauce tomate et riz', 'category': 'Viande', 'art_key': 'beef',
     'ingredients': ['Bœuf haché', 'Œuf', 'Oignon', 'Tomates concassées', 'Riz']},
    {'name': 'Poulet au curry et lait de coco', 'category': 'Viande', 'art_key': 'chicken',
     'ingredients': ['Poulet', 'Lait de coco', 'Curry', 'Oignon', 'Poivron', 'Riz']},
    {'name': 'Poulet mariné au citron et herbes, riz', 'category': 'Viande', 'art_key': 'chicken',
     'ingredients': ['Poulet', 'Citron', 'Ail', 'Herbes de Provence', "Huile d'olive", 'Riz']},
    {'name': 'Brochettes de bœuf, poivrons et oignons', 'category': 'Viande', 'art_key': 'skewer',
     'ingredients': ['Bœuf', 'Poivrons', 'Oignon', 'Cumin', 'Paprika', "Huile d'olive"]},
    {'name': 'Poulet aux olives et citron confit', 'category': 'Viande', 'art_key': 'chicken',
     'ingredients': ['Poulet', 'Olives', 'Citron confit', 'Oignon', 'Ail', 'Riz']},
    {'name': "Sauté d'agneau aux légumes printaniers", 'category': 'Viande', 'art_key': 'lamb',
     'ingredients': ['Agneau', 'Carottes', 'Petits pois', 'Oignon', 'Ail', "Huile d'olive"]},
    {'name': 'Hachis de bœuf, écrasé de patate douce', 'category': 'Viande', 'art_key': 'beef',
     'ingredients': ['Bœuf haché', 'Patate douce', 'Oignon', 'Tomates concassées', "Huile d'olive"]},
    {'name': 'Cabillaud vapeur, purée de patate douce', 'category': 'Poisson', 'art_key': 'fish',
     'ingredients': ['Cabillaud', 'Patate douce', 'Citron', "Huile d'olive"]},
    {'name': 'Saumon grillé, quinoa et brocolis', 'category': 'Poisson', 'art_key': 'fish',
     'ingredients': ['Saumon', 'Quinoa', 'Brocolis', 'Citron']},
    {'name': 'Papillote de dorade aux légumes', 'category': 'Poisson', 'art_key': 'fish',
     'ingredients': ['Dorade', 'Courgette', 'Tomate', 'Citron', 'Olives']},
    {'name': 'Curry de pois chiches et épinards', 'category': 'Végétarien', 'art_key': 'veggie',
     'ingredients': ['Pois chiches', 'Épinards', 'Lait de coco', 'Curry', 'Riz']},
    {'name': 'Chili végétarien (haricots rouges)', 'category': 'Végétarien', 'art_key': 'veggie',
     'ingredients': ['Haricots rouges', 'Maïs', 'Tomates concassées', 'Poivron', 'Riz']},
    {'name': 'Buddha bowl quinoa & légumes rôtis', 'category': 'Végétarien', 'art_key': 'veggie',
     'ingredients': ['Quinoa', 'Patate douce', 'Brocolis', 'Pois chiches', 'Tahini']},
    {'name': 'Galettes de lentilles corail', 'category': 'Végétarien', 'art_key': 'veggie',
     'ingredients': ['Lentilles corail', 'Carotte', 'Oignon', 'Œuf', 'Farine de riz']},
    {'name': 'Taboulé de boulgour, avocat et citron', 'category': 'Végétarien', 'art_key': 'veggie',
     'ingredients': ['Boulgour', 'Avocat', 'Citron', 'Oignon', 'Persil', "Huile d'olive"]},
    {'name': 'Velouté de courge butternut', 'category': 'Soupe', 'art_key': 'soup',
     'ingredients': ['Courge butternut', 'Oignon', 'Bouillon de légumes', 'Lait de coco']},
    {'name': 'Soupe de lentilles corail et carottes', 'category': 'Soupe', 'art_key': 'soup',
     'ingredients': ['Lentilles corail', 'Carottes', 'Oignon', 'Cumin', 'Bouillon de légumes']},
    {'name': 'Bouillon de poulet, légumes et vermicelles de riz', 'category': 'Soupe', 'art_key': 'soup',
     'ingredients': ['Poulet', 'Carottes', 'Vermicelles de riz', 'Bouillon de volaille']},
    {'name': 'Omelette aux légumes et pommes de terre', 'category': 'Autre', 'art_key': 'egg',
     'ingredients': ['Œufs', 'Pommes de terre', 'Oignon', 'Poivron', "Huile d'olive"]},
]

DEFAULT_GROCERY = [
    ('Fruits & légumes', ['Fruits de saison', 'Légumes de saison', 'Salade', 'Bananes']),
    ('Féculents & épicerie', ['Pain', 'Riz / pâtes', 'Farine', "Huile d'olive"]),
    ('Protéines', ['Viande / volaille', 'Poisson', 'Œufs', 'Légumineuses']),
    ('Produits laitiers', ['Lait', 'Yaourts', 'Fromage']),
    ('Hygiène & entretien', ['Produit vaisselle', 'Lessive', 'Papier toilette', 'Savon']),
]

DEFAULT_ACTIVITIES = []
