from django.urls import path
from . import views

urlpatterns = [
    path('', views.today, name='today'),
    path('toggle-task/', views.toggle_task, name='toggle_task'),
    path('timer-task/', views.timer_task, name='timer_task'),
    path('reorder-tasks/', views.reorder_tasks, name='reorder_tasks'),
    path('etoiles/', views.stars_view, name='stars'),
    path('semaine/', views.week_view, name='week'),
    path('semaine/dupliquer/', views.duplicate_week, name='duplicate_week'),
    path('maison/', views.maison, name='maison'),
    path('maison/toggle-course/', views.toggle_grocery, name='toggle_grocery'),
    path('maison/add-course/', views.add_grocery, name='add_grocery'),
    path('maison/reset-courses/', views.reset_grocery, name='reset_grocery'),
    path('maison/toggle-course-home/', views.toggle_grocery_home, name='toggle_grocery_home'),
    path('maison/edit-course/', views.edit_grocery, name='edit_grocery'),
    path('maison/delete-course/', views.delete_grocery, name='delete_grocery'),
    path('maison/toggle-rotation/', views.toggle_rotation, name='toggle_rotation'),
    path('menu/', views.menu, name='menu'),
    path('menu/toggle-favorite/', views.toggle_recipe_favorite, name='toggle_recipe_favorite'),
    path('reglages/', views.settings_view, name='settings'),
    path('reglages/activite/<int:pk>/supprimer/', views.delete_activity, name='delete_activity'),
    path('reglages/tache/<int:pk>/supprimer/', views.delete_custom_task, name='delete_custom_task'),
    path('reglages/tache/<int:pk>/modifier/', views.edit_custom_task, name='edit_custom_task'),
    path('reglages/membre/<int:pk>/retirer/', views.remove_member, name='remove_member'),
    path('reglages/membre/<int:pk>/promouvoir/', views.promote_member, name='promote_member'),
    path('reglages/membre/<int:pk>/enfant/', views.set_member_kid, name='set_member_kid'),
    path('reglages/exception/<int:pk>/reactiver/', views.reactivate_task_exception, name='reactivate_task_exception'),
    path('taches/exception/ajouter/', views.create_task_exception, name='create_task_exception'),
    path('taches/reassigner/', views.reassign_task, name='reassign_task'),
    path('taches/mode-jour/', views.set_day_mode, name='set_day_mode'),
    path('inscription/', views.signup, name='signup'),
    path('tablette/<str:token>/', views.tablet_view, name='tablet'),
]
