# Generated by Django 6.1 on 2026-09-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(choices=[('fille', 'Fille'), ('fils', 'Fils'), ('maman', 'Maman'), ('papa', 'Papa')], max_length=10)),
                ('day', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10)),
                ('period', models.CharField(choices=[('matin', 'Matin'), ('journee', 'Journée'), ('soir', 'Soir')], default='matin', max_length=10)),
                ('label', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['day', 'period', 'id'],
            },
        ),
    ]
