# Generated by Django 6.1 on 2026-09-02 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_customtask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('invite_code', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='taskcompletion',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='weeklymenuentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='activity',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.family'),
        ),
        migrations.AddField(
            model_name='customtask',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.family'),
        ),
        migrations.AddField(
            model_name='familysettings',
            name='family',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.family'),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.family'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.family'),
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.family'),
        ),
        migrations.AddField(
            model_name='weeklymenuentry',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.family'),
        ),
        migrations.AlterUniqueTogether(
            name='taskcompletion',
            unique_together={('family', 'person', 'date', 'task_id')},
        ),
        migrations.AlterUniqueTogether(
            name='weeklymenuentry',
            unique_together={('family', 'week_start', 'day')},
        ),
        migrations.CreateModel(
            name='FamilyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='planner.family')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
