# Generated by Django 6.1 on 2026-09-02 19:20

from django.db import migrations, models


def promote_existing_members(apps, schema_editor):
    # Accounts created before roles existed had full (parent-level) access —
    # keep it that way instead of silently demoting them to 'enfants'.
    FamilyMembership = apps.get_model('planner', 'FamilyMembership')
    FamilyMembership.objects.all().update(role='maman')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_require_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymembership',
            name='role',
            field=models.CharField(choices=[('maman', 'Maman'), ('papa', 'Papa'), ('enfants', 'Enfants')], default='enfants', max_length=10),
        ),
        migrations.RunPython(promote_existing_members, noop_reverse),
    ]
