# Generated by Django 6.1 on 2026-09-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_add_membership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='familysettings',
            name='maman_name',
            field=models.CharField(default='Maman', max_length=50),
        ),
        migrations.AddField(
            model_name='familysettings',
            name='maman_travaille',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='familysettings',
            name='nb_enfants',
            field=models.IntegerField(choices=[(1, '1 enfant'), (2, '2 enfants')], default=2),
        ),
    ]
