# Generated by Django 6.1 on 2026-09-15 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_family_settings_structural'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcompletion',
            name='seconds_spent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='timer_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TaskOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(choices=[('fille', 'Fille'), ('fils', 'Fils'), ('maman', 'Maman'), ('papa', 'Papa')], max_length=10)),
                ('task_id', models.CharField(max_length=60)),
                ('order', models.IntegerField(default=0)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.family')),
            ],
            options={
                'unique_together': {('family', 'person', 'task_id')},
            },
        ),
    ]
