# Generated by Django 6.1 on 2026-09-15 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_taskcompletion_seconds_spent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidStars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(choices=[('fille', 'Fille'), ('fils', 'Fils'), ('maman', 'Maman'), ('papa', 'Papa')], max_length=10)),
                ('total', models.PositiveIntegerField(default=0)),
                ('milestones_shown', models.PositiveIntegerField(default=0)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.family')),
            ],
            options={
                'verbose_name': 'Étoiles',
                'verbose_name_plural': 'Étoiles',
                'unique_together': {('family', 'person')},
            },
        ),
        migrations.CreateModel(
            name='StarAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(choices=[('fille', 'Fille'), ('fils', 'Fils'), ('maman', 'Maman'), ('papa', 'Papa')], max_length=10)),
                ('date', models.DateField()),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.family')),
            ],
            options={
                'unique_together': {('family', 'person', 'date')},
            },
        ),
    ]
