# Generated by Django 6.1 on 2026-09-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_kidstars_staraward'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='accompanied_by',
            field=models.CharField(blank=True, choices=[('fille', 'Fille'), ('fils', 'Fils'), ('maman', 'Maman'), ('papa', 'Papa')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='activity',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='items_to_bring',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='activity',
            name='picked_up_by',
            field=models.CharField(blank=True, choices=[('fille', 'Fille'), ('fils', 'Fils'), ('maman', 'Maman'), ('papa', 'Papa')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='activity',
            name='specific_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
