# Generated by Django 6.1 on 2026-09-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_migrate_activity_time_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='time',
        ),
    ]
