# Generated by Django 6.1 on 2026-09-16 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_activity_remove_old_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(choices=[('fille', 'Fille'), ('fils', 'Fils'), ('maman', 'Maman'), ('papa', 'Papa')], max_length=10)),
                ('task_id', models.CharField(max_length=60)),
                ('kind', models.CharField(choices=[('disabled_once', 'Désactivée pour ce jour'), ('disabled_from', 'Désactivée à partir de cette date'), ('not_applicable', "Non applicable ce jour (n'affecte pas le taux de complétion)")], max_length=20)),
                ('date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.family')),
            ],
            options={
                'indexes': [models.Index(fields=['family', 'person', 'task_id'], name='planner_tas_family__d6de94_idx')],
            },
        ),
    ]
