# Generated by Django 6.1 on 2026-09-16 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_task_exception'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(choices=[('fille', 'Fille'), ('fils', 'Fils'), ('maman', 'Maman'), ('papa', 'Papa')], max_length=10)),
                ('date', models.DateField()),
                ('mode', models.CharField(choices=[('normal', 'École normale'), ('vacances', 'Vacances'), ('absence', 'Absence'), ('allegee', 'Journée allégée')], default='normal', max_length=20)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.family')),
            ],
            options={
                'unique_together': {('family', 'person', 'date')},
            },
        ),
    ]
