# Generated by Django 6.1 on 2026-09-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    """Step 1/3 of the CustomTask day -> days conversion (routines-v2, multi-day custom
    tasks): add the new `days` field alongside the old `day` field. See
    0016_customtask_populate_days for the data migration and 0017_customtask_remove_day
    for dropping the old field once every row has been converted."""

    dependencies = [
        ('planner', '0014_day_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtask',
            name='days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
