# Generated by Django 6.1 on 2026-09-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_day_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymembership',
            name='kid_person',
            field=models.CharField(blank=True, choices=[('fille', 'Fille'), ('fils', 'Fils'), ('maman', 'Maman'), ('papa', 'Papa')], default='', max_length=10),
        ),
    ]
