# Generated by Django 6.1 on 2026-09-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_day_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='familysettings',
            name='star_milestone',
            field=models.PositiveIntegerField(default=15, help_text='Nombre de journées entièrement cochées avant la surprise.'),
        ),
        migrations.AddField(
            model_name='familysettings',
            name='star_reward_text',
            field=models.CharField(blank=True, default='', help_text='Texte affiché dans le popup de surprise (facultatif — sinon message générique).', max_length=200),
        ),
    ]
