# Generated by Django 6.1 on 2026-09-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0015_familysettings_star_milestone_and_reward_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='familysettings',
            name='tablet_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
