# Generated by Django 6.1 on 2026-09-16 15:00

from django.db import migrations


class Migration(migrations.Migration):
    """Step 3/3 of the CustomTask day -> days conversion: every row has been converted by
    0016_customtask_populate_days, so the old single-value `day` field can be dropped."""

    dependencies = [
        ('planner', '0016_customtask_populate_days'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customtask',
            options={'ordering': ['period', 'id']},
        ),
        migrations.RemoveField(
            model_name='customtask',
            name='day',
        ),
    ]
