# Generated by Django 6.1 on 2026-09-16 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0016_familysettings_tablet_token'),
        ('planner', '0016_migrate_ingredient_format'),
    ]

    operations = [
    ]
