# Generated by Django 6.1 on 2026-09-16 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0015_familymembership_kid_person'),
        ('planner', '0017_merge_20260916_2152'),
    ]

    operations = [
    ]
