# Generated by Django 6.1 on 2026-09-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    """Adds the 'reassigned' TaskException kind (point 5, routines-v2: handing a task to
    another family member for one day) plus the `reassigned_to` field it uses."""

    dependencies = [
        ('planner', '0017_customtask_remove_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexception',
            name='reassigned_to',
            field=models.CharField(
                blank=True, default='',
                choices=[('fille', 'Fille'), ('fils', 'Fils'), ('maman', 'Maman'), ('papa', 'Papa')],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name='taskexception',
            name='kind',
            field=models.CharField(
                choices=[
                    ('disabled_once', 'Désactivée pour ce jour'),
                    ('disabled_from', 'Désactivée à partir de cette date'),
                    ('not_applicable', "Non applicable ce jour (n'affecte pas le taux de complétion)"),
                    ('reassigned', 'Réattribuée à un autre membre pour ce jour'),
                ],
                max_length=20,
            ),
        ),
    ]
