# Generated by Django 6.1 on 2026-09-16 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0018_merge_20260916_2156'),
        ('planner', '0018_task_exception_reassign'),
    ]

    operations = [
    ]
