# Generated by Django 6.1 on 2026-09-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0019_merge_20260916_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daymode',
            name='mode',
            field=models.CharField(choices=[('normal', 'École normale'), ('vacances', 'Vacances'), ('absence', 'Absence'), ('allegee', 'Malade / Journée allégée')], default='normal', max_length=20),
        ),
    ]
