# Generated by Django 6.1 on 2026-09-17 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0020_alter_daymode_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymembership',
            name='kid_person',
        ),
    ]
