# Generated by Django 6.1 on 2026-09-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0021_remove_familymembership_kid_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='week_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
