# Generated by Django 6.1 on 2026-09-19 13:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0023_helprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='familysettings',
            name='quiet_end',
            field=models.TimeField(default=datetime.time(7, 0), help_text='Fin de la plage sans rappel (le matin).'),
        ),
        migrations.AddField(
            model_name='familysettings',
            name='quiet_start',
            field=models.TimeField(default=datetime.time(20, 30), help_text='Début de la plage sans rappel (le soir).'),
        ),
        migrations.AddField(
            model_name='familysettings',
            name='reminders_enabled',
            field=models.BooleanField(default=True, help_text="Afficher les rappels de routine des enfants dans l'application."),
        ),
        migrations.CreateModel(
            name='RoutineReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(choices=[('fille', 'Fille'), ('fils', 'Fils'), ('maman', 'Maman'), ('papa', 'Papa')], max_length=10)),
                ('phase', models.CharField(choices=[('matin', 'Matin'), ('journee', 'Journée'), ('soir', 'Soir')], default='matin', max_length=10)),
                ('at_time', models.TimeField()),
                ('days', models.JSONField(blank=True, default=list)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('acked_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.family')),
            ],
            options={
                'ordering': ['at_time', 'person', 'id'],
                'indexes': [models.Index(fields=['family', 'active'], name='planner_rou_family__111a60_idx')],
            },
        ),
    ]
