# Generated by Django 6.1 on 2026-09-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0024_familysettings_quiet_end_familysettings_quiet_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familysettings',
            name='household_servings',
            field=models.PositiveIntegerField(default=4, help_text='Nombre de personnes à table habituellement.'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.PositiveIntegerField(default=4, help_text='Nombre de personnes servies par les quantités indiquées.'),
        ),
        migrations.AddField(
            model_name='weeklymenuentry',
            name='leftovers_from',
            field=models.CharField(blank=True, choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='weeklymenuentry',
            name='servings',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
