# Generated by Django 6.1 on 2026-09-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0025_familysettings_household_servings_recipe_servings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtask',
            name='anchor_week',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtask',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Toutes les semaines'), ('biweekly', 'Une semaine sur deux'), ('monthly', 'Une fois par mois'), ('once', 'Une seule fois')], default='weekly', max_length=10),
        ),
        migrations.AddField(
            model_name='customtask',
            name='monthly_nth',
            field=models.IntegerField(blank=True, choices=[(1, 'Le 1er'), (2, 'Le 2e'), (3, 'Le 3e'), (4, 'Le 4e'), (-1, 'Le dernier')], null=True),
        ),
        migrations.AddField(
            model_name='customtask',
            name='specific_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
