# Generated by Django 6.1 on 2026-09-19 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0026_customtask_anchor_week_customtask_frequency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('items', models.JSONField(blank=True, default=list)),
                ('person', models.CharField(choices=[('fille', 'Fille'), ('fils', 'Fils'), ('maman', 'Maman'), ('papa', 'Papa')], default='fille', max_length=10)),
                ('period', models.CharField(choices=[('matin', 'Matin'), ('journee', 'Journée'), ('soir', 'Soir')], default='matin', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.family')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
